### ISSUE TITLE
Will the Celeb-Seq datasets be released?

### ISSUE THREAD

**Issue by SeuTao** [huangyangyu/SeqFace#1]

**Comment by huangyangyu** [comment]
Thanks for your attention, we have not decided whether to release the Celeb-Seq dataset.

**Comment by SeuTao** [comment]
thx

**Comment by thuhuwei** [comment]
Yes, we will release our codes, scripts, and models of other experiments described in the paper. Releasing the dataset might have commercial or copyright problems, so we have not decided.
