### ISSUE TITLE
cuda cudnn version

### ISSUE THREAD

**Issue by yemenr** [huangyangyu/SeqFace#7]
What's the right version of cuda and cudnn for the caffe compling?

**Comment by huangyangyu** [comment]
We compiled caffe in cuda-7.0 and cudnn-linux-x64-v4.0-prod.

**Comment by huangyangyu** [comment]
Moreover, we use cmake instead of makefile to compile the caffe under ubuntu 14.04. I think other environment is also ok.

**Comment by yemenr** [comment]
@huangyangyu thx~
